### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Bob Wen",
  "email": "wenmingzhi10@gmail.com",
  "address": "2040 JFK Blvd",
  "dateOfBirth": "1996-02-05",
  "registeredDate": "2025-10-31"
}

###