### GET request to example server
POST http://lb-2f0c46b5.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe Kafka Test",
  "email": "kafka_test4@example.com",
  "address": "123 Main St.",
  "dateOfBirth": "1005-09-09",
  "registeredDate": "2025-11-01"
}

###